### PR TITLE
Fix link for contributing.md

### PR DESCRIPTION
**Pull request by forresst**

### CODE REVIEW

**Comment by nkbt** [comment]
This should be generated by doctoc, not manually updated, use `npm run build:doc`, please.

**Comment by forresst** [comment]
Sorry, I only traversed the pages of Markdown. I have seen the use of tocdoc in npm scripts.  But I have not thought this page was auto-generated content.

**Comment by nkbt** [comment]
Ouch, I am very sorry, but this one is ok. It goes **after** auto-generated stuff

```
<!-- END doctoc ...
```

**Comment by nkbt** [comment]
Thanks for the fix!

**Comment by ericelliott** [comment]
:+1:

**Pull request merged**
