### PR TITLE
[#53] Fix environnment variables under Windows

### PR DESCRIPTION
**Pull request by forresst**
Screenshot with this PR under windows :
fixenv

This is a correction.

There may be a better solution?

### CODE REVIEW

**Comment by ericelliott** [comment]
@nkbt I don't have a working Windows install or VM to test this on at the moment. Do you have a way to verify this fix?

**Comment by ericelliott** [comment]
@forresst Could you link to a corresponding issue with a full description of the bug you're fixing?

**Comment by ericelliott** [comment]
https://github.com/cloverfield-tools/prod-module-boilerplate/issues/53

**Comment by ericelliott** [comment]
I know this is a bit confusing, (you caught us in the middle of moving), but you'll need to make this fix [here](https://github.com/cloverfield-tools/cf-package).

**Comment by forresst** [comment]
OK it's noted. I will do this asap

**Comment by nkbt** [comment]
I have a windows gaming rig, will be able to test these things. I am a little bit concerned with additional config introduced. Would prefer to add `./scripts` folder and use more native shell commands for windows and osx/linux.

**Comment by nkbt** [comment]
See http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/

**Comment by nkbt** [comment]
The other thing to be concerned - paths within app source. I try to use `path.join` and `path.resolve` whenever it is possible but still find from time to time some pieces of code with `/` in paths. Not an issue at the moment, but something to keep in mind if we are about to support windows.


I think it would be much better to create a simple docker container to run it on windows instead of trying to add all this magic to support it.

**Comment by nkbt** [comment]
One more thing to read http://shapeshed.com/writing-cross-platform-node/

**Comment by forresst** [comment]
Hi @nkbt and @ericelliott,

> **nkbt** : 
>See http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/

I know very well this post. (A bible for me :smile:) After reading this, I abandoned gulp, grunt and brunch

> **nkbt** :
> One more thing to read http://shapeshed.com/writing-cross-platform-node/

I just read it. Very interesting thank you. I learned very useful things.

> **nkbt** :
> The other thing to be concerned - paths within app source. I try to use path.join and path.resolve whenever it is possible but still find from time to time some pieces of code with / in paths. Not an issue at the moment, but something to keep in mind if we are about to support windows.

Yes ! Good Point !

> **nkbt**: 
> I am a little bit concerned with additional config introduced. Would prefer to add ./scripts folder and use more native shell commands for windows and osx/linux. 

No problem, it was a proposal, not the best solution. I will try to work in this direction. 

> **nkbt** : 
> I think it would be much better to create a simple docker container to run it on windows instead of trying to add all this magic to support it.

Can you explain `create a simple docker container`, i don't sure to understand the way ? It's the same principle of using the `.scripts` folder ?

> **ericelliott**:
I know this is a bit confusing, (you caught us in the middle of moving), but you'll need to make this fix here (cf-package).

Do I have the patch on both repository (prod-module-boilerplate and cf-package) ?

If the solution is to use a `.scripts` folder, so this means that we must add a `.scripts` folder in the `template` directory of `cf-package`.  That's ok for you ?

Finally, one should add the tests in a Windows VM. (For example, AppVeyor do it, see https://github.com/mozilla/nunjucks/blob/master/appveyor.yml for nunjucks repo)

**Comment by nkbt** [comment]
https://www.docker.com/

**Comment by forresst** [comment]
Thanks! I understood now.
But for me it is a very bad solution! Today I can use Yeoman directly under Windows without using Docker! I hope to use cf-package without Docker. What do you think ?

**Comment by nkbt** [comment]
You should be able to use it directly, but do development (builds and so
on) in a container

**Comment by forresst** [comment]
Ok I understand better. You have a project link that uses that ?

So for this PR, the solution :  `.scripts` folder or docker container ?

**Comment by nkbt** [comment]
I don't have open source examples available, what we do is in private repos
and quite specific to be shared as is.
https://docs.docker.com/installation/windows/

It is basically all devops work, not easy to start, but goes well after
everything is configured.



-- 
Sincerely yours, Nikita Butenko
Google Talk: nik@butenko.me
Skype: nikita.butenko
Mobile: +61 450 264 801

**Comment by nkbt** [comment]
I think it would be better to go `./scripts/*.js` way. Feels like less pain and easier to maintain. @ericelliott what do you reckon?

Something similar to 
https://github.com/gaearon/react-dnd/blob/master/package.json
https://github.com/gaearon/react-dnd/tree/master/scripts

**Comment by forresst** [comment]
Ok ! I await the opinion of @ericelliott  and I will do. Thank you very much for your patience and your help

**Comment by ericelliott** [comment]
> I think it would be better to go ./scripts/*.js way. Feels like less pain and easier to maintain. @ericelliott what do you reckon?

Agreed.

**Comment by ericelliott** [comment]
Also, let's move this and all future discussion about this project to [cf-package](https://github.com/cloverfield-tools/cf-package).

**Pull request closed without merging**
